### ISSUE TITLE
(CSS request) Is there a CSS to hide the fullscreen button

### ISSUE THREAD

**Issue by Mysticc28** [Spikerko/spicy-lyrics#145]
I've been searching for a way to hide the fullscreen button through a custom CSS snippet but haven't been succesful. Is there something that can help? Originally, through a marketplace CSS of hide fullscreen button it had gone away but after a recent update it came back

![Image](https://github.com/user-attachments/assets/5135e538-02d3-4ad9-a8a5-57214fe96871)

the button on the far left is the one I'm talking about.

**Comment by Spikerko** [comment]
@Mysticc28 To fully hide the smaller button, use this css:
```css
body:not(:has(.Root__main-view-overlay .BeautifulLyricsPage:is(.Fullscreen))) #BeautifulLyricsFullscreenButton {
  display: none !important;
}
```
